regions = ['Europe Paris eu-west-3', 'Europe London eu-west-2', 'Europe Spain eu-south-2', 'Europe Zurich eu-central-2', 'Europe Frankfurt eu-central-1']
raw_latencies = [
  [0, 6.81, 14.43, 10.16, 8.05],
  [6.87, 0, 20.88, 17.62, 12.48],
  [14.26, 20.59, 0, 30.13, 34.04],
  [9.96, 17.73, 30.73, 0, 7.37],
  [8.14, 12.42, 37.61, 7.34, 0]
]
