regions = [
    'ca-central-1',
    'eu-west-3',
    'ap-southeast-7',
    'ap-southeast-5',
    'ap-northeast-2',
]
raw_latencies = [
    [0, 42, 119.5, 112, 84.5],
    [42, 0, 91, 82.5, 128],
    [119.5, 91, 0, 11.28, 46.2],
    [112, 82.5, 11.29, 0, 36],
    [84.5, 128, 46.2, 36, 0],
]
