addresses = [
    ["127.0.0.1", 9876, ],
    ["127.0.0.1", 9877, ],
    ["127.0.0.1", 9878, ],
    ["127.0.0.1", 9879, ],
    ["127.0.0.1", 9880, ],
    ["127.0.0.1", 9881, ],
    ["127.0.0.1", 9882, ],
    ["127.0.0.1", 9883, ],
    ["127.0.0.1", 9884, ],
    ["127.0.0.1", 9885, ],
    ["127.0.0.1", 9886, ],
    ["127.0.0.1", 9887, ],
    ["127.0.0.1", 9888, ],
    ["127.0.0.1", 9889, ],
    ["127.0.0.1", 9890, ],
    ["127.0.0.1", 9891, ],
    ["127.0.0.1", 9892, ],
]
regions = [
    "us-west-2",
    "us-east-2",
    "ca-central-1",
    "mx-central-1",
    "eu-west-3",
    "eu-south-2",
    "eu-south-1",
    "eu-north-1",
    "eu-central-2",
    "eu-central-1",
    "me-central-1",
    "ap-southeast-3",
    "ap-southeast-7",
    "ap-southeast-2",
    "ap-southeast-4",
    "ap-east-1",
    "af-south-1",
]
raw_latencies = [
    [
        0.0,
        22.9,
        29.55,
        42.65,
        67.5,
        77.66,
        75.5,
        76.5,
        70.0,
        69.5,
        129.5,
        86.0,
        91.53,
        69.5,
        75.0,
        71.0,
        133.0,
    ],
    [
        22.9,
        0.0,
        11.65,
        24.24,
        46.8,
        61.0,
        56.0,
        56.0,
        50.5,
        49.35,
        102.5,
        107.75,
        113.5,
        93.0,
        98.5,
        96.0,
        115.0,
    ],
    [
        29.55,
        11.65,
        0.0,
        33.65,
        41.89,
        53.5,
        50.5,
        52.5,
        45.65,
        44.65,
        97.5,
        113.5,
        119.0,
        98.0,
        103.07,
        102.0,
        111.0,
    ],
    [
        42.65,
        24.25,
        33.66,
        0.0,
        68.0,
        79.5,
        77.03,
        77.15,
        72.5,
        71.0,
        124.5,
        124.5,
        135.0,
        104.89,
        110.0,
        105.39,
        133.5,
    ],
    [
        67.5,
        46.8,
        41.89,
        68.0,
        0.0,
        7.1,
        9.96,
        15.13,
        4.79,
        4.15,
        56.5,
        90.5,
        96.5,
        134.5,
        140.5,
        100.0,
        72.5,
    ],
    [
        77.63,
        61.0,
        53.5,
        79.5,
        7.1,
        0.0,
        12.75,
        27.87,
        15.95,
        16.85,
        58.22,
        81.5,
        87.5,
        119.5,
        126.5,
        89.0,
        72.5,
    ],
    [
        75.32,
        56.0,
        50.5,
        77.0,
        9.97,
        12.75,
        0.0,
        15.15,
        2.49,
        5.38,
        53.5,
        82.0,
        87.5,
        119.5,
        125.0,
        91.0,
        91.05,
    ],
    [
        76.5,
        55.05,
        52.5,
        77.5,
        15.12,
        27.89,
        15.15,
        0.0,
        13.88,
        10.36,
        67.0,
        96.0,
        102.5,
        134.0,
        138.5,
        105.0,
        85.5,
    ],
    [
        70.0,
        50.5,
        45.64,
        72.05,
        4.79,
        15.95,
        2.48,
        13.87,
        0.0,
        3.42,
        55.0,
        83.5,
        90.5,
        121.5,
        126.5,
        94.0,
        74.5,
    ],
    [
        69.5,
        49.35,
        44.62,
        71.0,
        4.14,
        16.84,
        5.44,
        10.35,
        3.41,
        0.0,
        58.0,
        86.0,
        92.5,
        124.0,
        129.5,
        96.5,
        77.5,
    ],
    [
        129.5,
        101.5,
        97.5,
        124.5,
        56.5,
        58.18,
        53.5,
        67.0,
        55.0,
        58.0,
        0.0,
        52.54,
        57.0,
        89.0,
        93.5,
        60.5,
        63.0,
    ],
    [
        86.0,
        107.76,
        113.5,
        124.5,
        90.5,
        81.5,
        82.0,
        96.0,
        83.5,
        86.0,
        52.5,
        0.0,
        20.55,
        54.0,
        58.52,
        26.04,
        109.0,
    ],
    [
        91.51,
        113.5,
        119.0,
        135.0,
        96.5,
        87.5,
        87.5,
        102.5,
        90.5,
        92.5,
        57.0,
        20.56,
        0.0,
        59.41,
        65.0,
        31.11,
        115.5,
    ],
    [
        69.5,
        93.0,
        98.0,
        104.87,
        135.0,
        119.5,
        119.5,
        134.0,
        121.5,
        124.0,
        89.0,
        54.0,
        59.36,
        0.0,
        5.25,
        62.5,
        147.0,
    ],
    [
        75.0,
        98.5,
        103.04,
        110.0,
        141.5,
        126.5,
        125.0,
        138.5,
        126.52,
        129.5,
        93.5,
        58.5,
        65.0,
        5.25,
        0.0,
        69.0,
        151.5,
    ],
    [
        71.0,
        96.0,
        102.5,
        105.41,
        100.0,
        89.0,
        91.0,
        105.0,
        94.0,
        96.5,
        61.0,
        26.05,
        31.11,
        62.5,
        69.0,
        0.0,
        120.0,
    ],
    [
        133.0,
        115.0,
        111.0,
        133.5,
        72.5,
        72.5,
        91.05,
        85.5,
        74.5,
        77.5,
        63.0,
        109.0,
        115.5,
        147.0,
        151.51,
        120.0,
        0.0,
    ],
]
