addresses = [
    ["127.0.0.1", 9876, ],
    ["127.0.0.1", 9877, ],
    ["127.0.0.1", 9878, ],
]
regions = [
    "ap-southeast-3",
    "ap-southeast-7",
    "ap-east-1",
]
raw_latencies = [
    [
        0.0,
        20.55,
        26.04,
    ],
    [
        20.56,
        0.0,
        31.11,
    ],
    [
        26.05,
        31.11,
        0.0,
    ],
]
