addresses = [
    ["127.0.0.1", 9876, ],
    ["127.0.0.1", 9877, ],
    ["127.0.0.1", 9878, ],
    ["127.0.0.1", 9879, ],
    ["127.0.0.1", 9880, ],
]
regions = [
    "us-west-2",
    "mx-central-1",
    "ap-southeast-3",
    "ap-southeast-7",
    "ap-east-1",
]
raw_latencies = [
    [
        0.0,
        42.65,
        86.0,
        91.53,
        71.0,
    ],
    [
        42.65,
        0.0,
        124.5,
        135.0,
        105.39,
    ],
    [
        86.0,
        124.5,
        0.0,
        20.55,
        26.04,
    ],
    [
        91.51,
        135.0,
        20.56,
        0.0,
        31.11,
    ],
    [
        71.0,
        105.41,
        26.05,
        31.11,
        0.0,
    ],
]
