regions = [
    'ap-east-1 Asia Pacific Hong Kong',
    'ap-east-2 Asia Pacific Taipei',
    'ap-northeast-1 Asia Pacific Tokyo',
    'ap-northeast-2 Asia Pacific Seoul',
    'ap-northeast-3 Asia Pacific Osaka',
    'ap-southeast-1 Asia Pacific Singapore',
    'ap-southeast-5 Asia Pacific Malaysia',
]
raw_latencies = [
    [0, 7.11, 26.28, 18.23, 27.31, 18.81, 19.38],
    [7.1, 0, 15.6, 29.73, 15.3, 22, 24.96],
    [26.12, 15.48, 0, 16.15, 4.27, 34.15, 36.08],
    [18.2, 29.75, 16.16, 0, 8.05, 33.17, 37.31],
    [27.3, 15.3, 4.29, 8.05, 0, 37, 40.18],
    [18.8, 22, 34.17, 33.17, 37, 0, 3.83],
    [19.37, 24.96, 36.1, 37.31, 40.15, 3.81, 0],
]
