regions = [
    'ap-east-1 Asia Pacific Hong Kong',
    'ap-east-2 Asia Pacific Taipei',
    'ap-northeast-1 Asia Pacific Tokyo',
    'ap-northeast-2 Asia Pacific Seoul',
    'ap-northeast-3 Asia Pacific Osaka',
    'ap-southeast-1 Asia Pacific Singapore',
    'ap-southeast-5 Asia Pacific Malaysia',
]
raw_latencies = [
    [0, 7.37, 26.02, 18.57, 28.4, 15.76, 20.56],
    [7.37, 0, 16.59, 29.98, 15.31, 21.83, 24.88],
    [26.03, 16.59, 0, 16.25, 4.72, 34.48, 36.42],
    [18.56, 30, 16.23, 0, 8.45, 33.79, 36.6],
    [28.4, 15.31, 4.78, 8.45, 0, 37.5, 39.3],
    [15.77, 21.83, 34.49, 33.79, 37.5, 0, 3.68],
    [20.57, 24.88, 36.43, 36.61, 39.3, 3.67, 0],
]
