addresses = [
    ["127.0.0.1", 9876, ],
    ["127.0.0.1", 9877, ],
    ["127.0.0.1", 9878, ],
]
regions = [
    "eu-west-3",
    "eu-west-2",
    "eu-central-2",
]
raw_latencies = [
    [
        0.0,
        3.47,
        4.78,
    ],
    [
        3.47,
        0.0,
        8.46,
    ],
    [
        4.79,
        8.46,
        0.0,
    ],
]
