addresses = [
    ["127.0.0.1", 9876, ],
    ["127.0.0.1", 9877, ],
    ["127.0.0.1", 9878, ],
    ["127.0.0.1", 9879, ],
    ["127.0.0.1", 9880, ],
]
regions = [
    "eu-west-3",
    "eu-west-2",
    "eu-west-1",
    "eu-central-2",
    "eu-central-1",
]
raw_latencies = [
    [
        0.0,
        3.47,
        9.31,
        4.78,
        3.98,
    ],
    [
        3.47,
        0.0,
        4.58,
        8.46,
        6.32,
    ],
    [
        9.3,
        4.58,
        0.0,
        14.3,
        10.7,
    ],
    [
        4.79,
        8.46,
        14.3,
        0.0,
        3.56,
    ],
    [
        4.13,
        6.31,
        10.72,
        3.6,
        0.0,
    ],
]
