---
- name: Prepare all nodes (Cassandra, Binaries)
  hosts: kcensus_nodes
  gather_facts: no
  strategy: free
  serial: 0
  tasks:
    - name: Wait for SSH to become available
      wait_for:
        host: "{{ inventory_hostname }}"
        port: 22
        state: started
      delegate_to: localhost

    - name: Create a directory for the application
      ansible.builtin.file:
        path: /home/ec2-user/kcensus_app
        state: directory
        mode: '0755'

    - name: Copy the kcensus binary
      ansible.builtin.copy:
        src: ../../target/x86_64-unknown-linux-musl/release/kcensus
        dest: /home/ec2-user/kcensus_app/kcensus
        mode: '0755'

    # Note: graph_bench is copied in its specific experiment
