---
- name: Run kcensus Experiment and Collect Results
  hosts: all
  gather_facts: no
  vars:
    # default values: will always be overriden
    algo: "kcensus"
    writes: "1"
    duration: "10s"
    ingress: "exponential"
    throughput: "10"
    speedup: "1"
    faults: ""
    keys: "100"
    skew: "0"
    shards: "100"
    nonvoting: ""
    conflicts: ""
    result_path: "./results_default"

  tasks:
    - name: Set sub_exp_id for regular inventory (fallback to host index)
      set_fact:
        sub_exp_id: "{{ sub_exp_id | default(groups['kcensus_nodes'].index(inventory_hostname) if 'kcensus_nodes' in groups else groups['all'].index(inventory_hostname)) }}"
        cassandra_port: "{{ cassandra_port | default(9041 + (groups['kcensus_nodes'].index(inventory_hostname) if 'kcensus_nodes' in groups else groups['all'].index(inventory_hostname)) + 1) }}"

    - name: Run kcensus
      ansible.builtin.shell:
        cmd: >
          RUST_BACKTRACE=1 timeout 60s /usr/bin/time -f "[time] Memory(KB): %M"
          ./kcensus --config config.toml -p {{ sub_exp_id }}
          -a "{{ algo }}"
          -w "{{ writes }}"
          --duration "{{ duration }}"
          -i "{{ ingress }}"
          -t "{{ throughput }}"
          -s "{{ speedup }}"
          -k "{{ keys }}"
          --skew "{{ skew }}"
          --shards "{{ shards }}"
          {{ "-v " + nonvoting if nonvoting else "" }}
          {{ "-f " + faults if faults else "" }}
          {{ "--conflicts=" + conflicts if conflicts else "" }}
        chdir: /home/ec2-user/kcensus_app
      register: job_result

    - name: Save output from each server
      delegate_to: localhost
      ansible.builtin.copy:
        dest: "{{ result_path }}/server_{{ sub_exp_id }}.log"
        content: |
          STDOUT:
          {{ job_result.stdout | default('NO STDOUT CAPTURED') }}

          STDERR:
          {{ job_result.stderr | default('NO STDERR CAPTURED') }}
