---
- name: Forcefully Terminate Experiment Processes
  hosts: kcensus_nodes
  gather_facts: no
  strategy: free
  tasks:
    - name: Kill any running kcensus processes
      ansible.builtin.shell:
        cmd: "pkill -f kcensus"
      register: pkill_result
      failed_when: "pkill_result.rc != 0 and pkill_result.rc != 1"
      changed_when: pkill_result.rc == 0

# this file will be used in case of errors in order to clean up the
# environment and rerun experiments