---
- name: Prepare and distribute TOML configs
  hosts: all
  gather_facts: no
  vars:
    config_path: "/tmp/config.toml"
    master_config_path: "/tmp/master-config.json"

  tasks:
    - name: Load master-config.json on controller
      delegate_to: localhost
      run_once: true
      ansible.builtin.set_fact:
        master_cfg: "{{ lookup('file', master_config_path) | from_json }}"

    - name: Find current host in master config and extract info
      set_fact:
        cassandra_port: "{{ (master_cfg.nodes | selectattr('ip', 'equalto', inventory_hostname) | first).cassandra_port }}"
        global_id: "{{ (master_cfg.nodes | selectattr('ip', 'equalto', inventory_hostname) | first).global_id }}"
        local_sub_exp_id: "{{ sub_exp_id }}"

    - name: Generate per-node config locally
      delegate_to: localhost
      run_once: false
      ansible.builtin.shell: >
        {{ playbook_dir }}/scripts/modify_config.py
        {{ config_path }}
        {{ sub_exp_id }}
      args:
        chdir: "{{ playbook_dir }}"
      register: patched_conf
      changed_when: false

    - name: Push personalized config.toml to remote
      ansible.builtin.copy:
        dest: /home/ec2-user/kcensus_app/config.toml
        mode: '0644'
        content: "{{ patched_conf.stdout }}"