---
- name: Run a kcensus sub-experiment
  hosts: all
  gather_facts: no
  vars:
    algo:             "k-census"
    writes:           "1"
    requests:         "100"
    ingress:          "round-robin"
    throughput:       "0"
    speedup:          "1"
    faults:           ""
    master_config_path: "/tmp/master-config.json"

  tasks:
    - name: Load master-config.json on controller
      delegate_to: localhost
      run_once: true
      ansible.builtin.set_fact:
        master_cfg: "{{ lookup('file', master_config_path) | from_json }}"

    - name: Find current host in master config and extract info
      set_fact:
        cassandra_port: "{{ (master_cfg.nodes | selectattr('ip', 'equalto', inventory_hostname) | first).cassandra_port }}"
        global_id: "{{ (master_cfg.nodes | selectattr('ip', 'equalto', inventory_hostname) | first).global_id }}"
        local_sub_exp_id: "{{ sub_exp_id }}"

    - name: Start kcensus process in the background
      ansible.builtin.shell:
        cmd: >
          /usr/bin/time -f "[time] Memory(KB): %M"
          ./kcensus --config config.toml -p {{ sub_exp_id }}
          -d 127.0.0.1:{{ cassandra_port }}
          -a "{{ algo }}"
          -w "{{ writes }}"
          -r "{{ requests }}"
          -i "{{ ingress }}"
          -t "{{ throughput }}"
          -s "{{ speedup }}"
          {{ "-f " + faults if faults else "" }}
        chdir: /home/ec2-user/kcensus_app
      async: 7200
      poll: 0
      register: kcensus_async_start

- name: Wait for kcensus to finish
  hosts: all
  gather_facts: no
  strategy: free
  tasks:
    - name: Wait for process to finish
      ansible.builtin.async_status:
        jid: "{{ hostvars[inventory_hostname]['kcensus_async_start'].ansible_job_id }}"
      register: job_result
      until: job_result.finished
      retries: 600
      delay: 12

- name: Save kcensus results locally
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    result_path: "./results_default"  # overridden
  tasks:
    - name: Create local results directory
      ansible.builtin.file:
        path: "{{ result_path }}"
        state: directory
        mode: '0755'
      run_once: true

    - name: Save output from each server
      ansible.builtin.copy:
        dest: "{{ result_path }}/server_{{ hostvars[item]['local_sub_exp_id'] | default(hostvars[item]['global_id']) }}.log"
        content: |
          STDOUT:
          {{ hostvars[item]['job_result'].stdout | default('NO STDOUT CAPTURED') }}

          STDERR:
          {{ hostvars[item]['job_result'].stderr | default('NO STDERR CAPTURED') }}
      loop: "{{ groups['all'] }}"
      loop_control:
        label: "{{ item }}"