# This playbook orchestrates the execution and collection of results for experiments.
# 3 main phases: starting the processes, waiting for them to complete,
# saving the individual results locally.

- name: Start Experiments Sequentially
  hosts: kcensus_nodes
  gather_facts: no
  order: inventory
  serial: 1
  vars: # these are just defaults to avoid errors, most of them are overriden
    algo: "k-census"
    writes: "1"
    requests: "100"
    ingress: "round-robin"
    throughput: "0"
    faults: ""

  tasks:
    - name: Start kcensus process in the background
      ansible.builtin.shell:
        cmd: >
          /usr/bin/time -f "[time] Memory(KB): %M" 
          ./kcensus --config config.toml -p {{ groups['kcensus_nodes'].index(inventory_hostname) }}
          -d 127.0.0.1:{{ 9041 + groups['kcensus_nodes'].index(inventory_hostname) + 1 }}
          -a "{{ algo }}"
          -w "{{ writes }}"
          -r "{{ requests }}"
          -i "{{ ingress }}"
          -t "{{ throughput }}"
          {{ "-f " + faults if faults else "" }}
        chdir: /home/ec2-user/kcensus_app
      async: 7200 # 2 hours
      poll: 0
      register: kcensus_async_start

    - name: Print async job ID for reference
      ansible.builtin.debug:
        msg: "Started kcensus on {{ inventory_hostname }} with Job ID {{ kcensus_async_start.ansible_job_id }}"


- name: Wait For Experiments to Finish
  hosts: kcensus_nodes
  gather_facts: no

  tasks:
    - name: Wait for kcensus process on this host to finish
      ansible.builtin.async_status:
        jid: "{{ hostvars[inventory_hostname]['kcensus_async_start'].ansible_job_id }}"
      register: job_result
      until: job_result.finished
      retries: 600
      delay: 12


- name: Save Individual Results Locally
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    # default path (will always be overridden)
    result_path: "./results_default"

  tasks:
    - name: Create local results directory
      ansible.builtin.file:
        path: "{{ result_path }}"
        state: directory
        mode: '0755'
      run_once: true

    - name: Save output from each server to a file
      ansible.builtin.copy:
        dest: "{{ result_path }}/server_{{ groups['kcensus_nodes'].index(item) }}.log"
        content: |

          STDOUT:
          {{ hostvars[item]['job_result'].stdout | default('NO STDOUT CAPTURED') }}

          STDERR:
          {{ hostvars[item]['job_result'].stderr | default('NO STDERR CAPTURED') }}
      loop: "{{ groups['kcensus_nodes'] }}"
      loop_control:
        label: "{{ item }}"

    - name: Display final message
      ansible.builtin.debug:
        msg: "All experiment results have been saved in the {{ result_path }} directory."
      run_once: true