- name: Stop experiments forcefully
  hosts: kcensus_nodes
  gather_facts: no

  tasks:
    - name: Terminate any running kcensus processes using pkill
      ansible.builtin.command:
        cmd: pkill kcensus
      register: pkill_result
      failed_when: "pkill_result.rc > 1"
      changed_when: "pkill_result.rc == 0"

    - name: Report status
      ansible.builtin.debug:
        msg: >-
          {% if pkill_result.rc == 0 -%}
          kcensus process found and terminated on {{ inventory_hostname }}.
          {% elif pkill_result.rc == 1 -%}
          No kcensus process was running on {{ inventory_hostname }}.
          {%- endif %}